postgres:
  build: database/
  env_file: .env
  ports:
    - "5432:5432"
web:
  build: .
  env_file: .env
  ports:
    - "80:80"
  volumes:
    - ./rest_user_groups:/srv/app/rest_user_groups
  links:
    - postgres
